@artists_favorites_api_HostAddress = http://localhost:5125
@artist_name = mf doom

GET {{artists_favorites_api_HostAddress}}/v1/search/{{artist_name}}
Accept: application/json

###

GET {{artists_favorites_api_HostAddress}}/initiate-authorize
