@artists_favorites_api_HostAddress = http://localhost:5125
@artist_name = mf doom

# OAuth2.0 access token we got after user authorization.
# Try not to commit or better yet use environments instead of hardcoding here, I am just lazy lol :).
@resources_access_token = "****"


# @name getArtistByName
GET {{artists_favorites_api_HostAddress}}/v1/search/{{artist_name}}
Accept: application/json

###

# @name initiateAuthorize
GET {{artists_favorites_api_HostAddress}}/initiate-authorize

@spotifyAuthorizeUrl = {{ initiateAuthorize.response.body.$.spotifyAuthorizeUrl }}

###

# @name createEmptyPlaylist
POST {{artists_favorites_api_HostAddress}}/v1/playlist/create
Accept: application/json
Content-Type: application/json
Authorization: "Bearer {{ resources_access_token }}"
{
    "playlistName": "Test - {{$guid}}",
    "playlistDescription": "Tested locally",
    "isPublicPlaylist": true
}

@emptyPlaylistResponseStringJson = {{ createEmptyPlaylist.response.body }}
